create table public.event_series (
  id bigint generated by default as identity primary key,
  organizer_id bigint not null references public.organizers(id),
  title text,
  generation_type text not null check (generation_type in ('WEEKLY', 'MULTIPLE_DATES')),
  recurrence_start_date date,
  recurrence_end_date date,
  weekdays smallint[],
  event_duration_days smallint not null default 1 check (event_duration_days > 0),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.events
  add column start_date date,
  add column end_date date,
  add column series_id bigint references public.event_series(id) on delete set null;

update public.events
set start_date = (start_time at time zone 'Europe/Copenhagen')::date,
    end_date = coalesce((end_time at time zone 'Europe/Copenhagen')::date, (start_time at time zone 'Europe/Copenhagen')::date);

alter table public.events
  alter column start_date set not null,
  alter column end_date set not null;

create index events_series_id_idx on public.events(series_id);
create index event_series_organizer_id_idx on public.event_series(organizer_id);

alter table public.event_series enable row level security;

create policy "Event series are readable by everyone"
  on public.event_series for select using (true);

create policy "Admins can manage event series"
  on public.event_series for all
  using ((select role from public.profiles where id = auth.uid()) = 'admin')
  with check ((select role from public.profiles where id = auth.uid()) = 'admin');

create policy "Organizers can create their event series"
  on public.event_series for insert
  with check (created_by = auth.uid() and (select role from public.profiles where id = auth.uid()) = 'organizer');

create policy "Organizers can manage their event series"
  on public.event_series for update
  using (created_by = auth.uid() and (select role from public.profiles where id = auth.uid()) = 'organizer')
  with check (created_by = auth.uid() and (select role from public.profiles where id = auth.uid()) = 'organizer');

create policy "Organizers can delete their event series"
  on public.event_series for delete
  using (created_by = auth.uid() and (select role from public.profiles where id = auth.uid()) = 'organizer');
